#ifndef SERVER_CONSTANTS
#define SERVER_CONSTANTS


#define INITIAL_PROMPT "\n\n\n----------------------------Welcome to the bank!----------------------\nChoose your position in the bank \n\n\n1.\tAdmin\n2.\tCustomer\n3.\tEmployee\n4.\tManager\nPress any other number to exit\nEnter the number corresponding to the choice!"

// ========== COMMON TEXT =============================

// LOGIN
#define ADMIN_CREDENTIALS_FILE "./admin/admincred.h"
#define LOGIN_ID "Enter your login ID"
#define PASSWORD "Enter your password \n# "
#define INVALID_LOGIN "The login ID specified doesn't exist!$"
#define INVALID_PASSWORD "The password specified doesn't match!$"
#define SALT_BAE "666"


#define MANAGER_LOGIN_WELCOME "Welcome Manager! \nEnter your credentials"
#define MANAGER_LOGIN_SUCCESS "Welcome manager!"
#define EMPLOYEE_LOGIN_ID_DOESNT_EXIST "Employee ID does not exist!"
#define MANAGER_LOGIN_ID_DOESNT_EXIST "Manager ID does not exist!"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIST "the id you entered does not exist"
#define EMPLOYEE_LOGIN_WELCOME "Welcome dear employee! \nEnter your credentials "
#define  EMPLOYEE_LOGIN_SUCCESS "Welcome EMPLOYEE!"


// GET ACCOUNT DETAILS
#define GET_ACCOUNT_NUMBER "Enter the account id \n\t(eg sampath-1   for name sampath and account no 1) "
#define GET_CUSTOMER_ID "Enter the customer ID of the customer you're searching for"

#define ERRON_INPUT_FOR_NUMBER "It seems you have passed a sequence of alphabets when a number was expected or you have entered an invalid number!\nYou'll now be redirected to the main menu!^"

#define INVALID_MENU_CHOICE "It seems you've made an invalid menu choice\nYou'll now be redirected to the main menu!^"

#define CUSTOMER_ID_DOESNT_EXIT "No customer could be found for the given ID"
#define CUSTOMER_LOGIN_ID_DOESNT_EXIT "No customer could be found for the given login ID$"
#define EMPLOYEE_ID_DOESNT_EXIT "No employee could be found for the given  ID"
#define EMPLOYEE_LOGIN_ID_DOESNT_EXIT "No employee could be found for the given login ID$"
#define GET_EMPLOYEE_NUMBER "Enter the employee login id \n\t(eg sampath-1   for name sampath and account no 1) "
#define ACCOUNT_ID_DOESNT_EXIT "No account could be found for the given account number"
#define EMPLOYEE_LOGOUT "Logging you out now dear employee! Good bye!$"
#define  MANAGER_LOGOUT "Logging you out now dear manager! Good bye!$"

#define TRANSACTIONS_NOT_FOUND "No transactions were performed on this account by the customer!^"

// ====================================================

// ========== ADMIN SPECIFIC TEXT======================

// LOGIN WELCOME
#define ADMIN_LOGIN_WELCOME "Welcome dear admin! \nEnter your credentials "
#define ADMIN_LOGIN_SUCCESS "Welcome Admin!"

// ADMIN MENU
#define ADMIN_MENU "\t1.\tAdd new Customer\n\t2\tModify customer details \n\t3.\tGet customer details \n\t4.\tGet transation details \n\t5.\tDeactivate customer account \n\t6.\tAdding new employee  \n\t7.\tModify employee information\n\t8.\tGet Employee details \n\t9.\tChange Manager roles\n\t10\tChange Admin password \n\tPress any other key to logout\n\t"
#define EMPLOYEE_MENU "\t1.\tAdd new Customer\n\t2.\tget account details\n\t3.accept_reject_loan_applications\t \n\t4.\tModify customer details \n\t5.process Loan Applications \n\t7.\t View Assigned Loan applications\n\t8.view Customer Transactions \n\t 9.change password\n\tPress any other key to logout\n\t"
#define MANAGER_MENU "\t1.Activate/Deactivate Customer Accounts\n\t2.\tAssign Loan Application Processes to Employees\n\t3.Review Customer Feedback\t \n\t4.\tChange Password  \n\t Press any other key to logout\n\t"
// ADD CUSTOMER

#define ADMIN_ADD_CUSTOMER_NAME "What is the customer's name?"
#define ADMIN_ADD_CUSTOMER_GENDER "What is the customer's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_CUSTOMER_AGE "What is the customer's age?"
#define ADMIN_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is : "
#define AUTOGEN_PASSWORD "0000" // append to end of next string macro
#define ADMIN_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define ADMIN_ADD_CUSTOMER_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"

#define EMPLOYEE_ADD_CUSTOMER_GENDER "What is the customer's gender?\nEnter M for male, F for female and O for others"
#define EMPLOYEE_ADD_CUSTOMER_NAME "What is the customer's name?"
#define EMPLOYEE_ADD_CUSTOMER_AGE "What is the customer's age?"
#define EMPLOYEE_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is : "
#define AUTOGEN_PASSWORD "0000" // append to end of next string macro
#define EMPLOYEE_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define EMPLOYEE_ADD_CUSTOMER_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"

// ADD EMPLOYEE

#define ADMIN_ADD_EMPLOYEE_NAME "What is the employee's name?"
#define ADMIN_ADD_EMPLOYEE_GENDER "What is the employee's gender?\nEnter M for male, F for female and O for others"
#define ADMIN_ADD_EMPLOYEE_AGE "What is the employee's age?"
#define ADMIN_ADD_EMPLOYEE_AUTOGEN_LOGIN "The autogenerated login ID for the employee is : "
#define AUTOGEN_PASSWORD "0000" // append to end of next string macro
#define ADMIN_ADD_EMPLOYEE_AUTOGEN_PASSWORD "The autogenerated password for the employee is : "
#define ADMIN_ADD_EMPLOYEE_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"
#define ADMIN_ADD_EMPLOYEE_NUMBER "The newly joined employee's number is :"


#define ADMIN_ADD_MANAGER_AUTOGEN_PASSWORD "The autogenerated password for the manager is : "

// ADD ACCOUNT
// #define ADMIN_ADD_ACCOUNT_TYPE "What type of account is to be created? Enter 1 for regular account and 2 for joint account"
#define ADMIN_ADD_ACCOUNT_NUMBER "The newly created account's number is :"
#define EMPLOYEE_ADD_ACCOUNT_NUMBER "The newly created account's number is :"


// DELETE ACCOUNT
#define ADMIN_DEL_ACCOUNT_NO "What is the account number of the account you want to delete?"
#define ADMIN_DEL_ACCOUNT_SUCCESS "This account has been successfully deleted\nRedirecting you to the main menu ...^"
#define ADMIN_DEL_ACCOUNT_FAILURE "This account cannot be deleted since it still has some money\nRedirecting you to the main menu ...^"

// MODIFY CUSTOMER INFO
#define ADMIN_MOD_CUSTOMER_ID "Enter the ID of the customer who's information you want to edit"
#define ADMIN_MOD_CUSTOMER_MENU "Which information would you like to modify?\n1. Name \n2. Age \n3. Gender \n4.Reset customer password\nPress any other key to cancel"
#define ADMIN_MOD_CUSTOMER_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_CUSTOMER_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_CUSTOMER_NEW_AGE "What's the updated value for age?"

#define EMPLOYEE_MOD_CUSTOMER_ID "Enter the ID of the customer who's information you want to edit"
#define EMPLOYEE_MOD_CUSTOMER_MENU "Which information would you like to modify?\n1. Name \n2. Age \n3. Gender \n4.Reset customer password\nPress any other key to cancel"
#define EMPLOYEE_MOD_CUSTOMER_NEW_NAME "What's the updated value for name?"
#define EMPLOYEE_MOD_CUSTOMER_NEW_GENDER "What's the updated value for gender?"
#define EMPLOYEE_MOD_CUSTOMER_NEW_AGE "What's the updated value for age?"

#define ADMIN_MOD_CUSTOMER_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"
#define EMPLOYEE_MOD_CUSTOMER_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"
#define ADMIN_LOGOUT "Logging you out now Admin! Good bye!$"


// MODIFY EMPLOYEE INFO
#define ADMIN_MOD_EMPLOYEE_ID "Enter the ID of the employee who's information you want to edit"
#define ADMIN_MOD_EMPLOYEE_MENU "Which information would you like to modify?\n1. Name \n2. Age \n3. Gender \n4.Reset employee password\nPress any other key to cancel"
#define ADMIN_MOD_EMPLOYEE_NEW_NAME "What's the updated value for name?"
#define ADMIN_MOD_EMPLOYEE_NEW_GENDER "What's the updated value for gender?"
#define ADMIN_MOD_EMPLOYEE_NEW_AGE "What's the updated value for age?"

#define ADMIN_MOD_EMPLOYEE_SUCCESS "The required modification was successfully made!\nYou'll now be redirected to the main menu!^"

// MODIFY EMPLOYEE ROLES
#define ADMIN_MOD_EMPLOYEE_NO "What is the employee id  of the employee you want to manage the roles?"
#define ADMIN_MOD_EMPLOYEE_FAILURE "This account cannot be modified \nRedirecting you to the main menu ...^"



//================================================
//====== CUSTOMER SPECIFIC TEXT===================

// LOGIN WELCOME
#define CUSTOMER_LOGIN_WELCOME "Welcome dear customer! Enter your credentials to gain access to your account!"
#define CUSTOMER_LOGIN_SUCCESS "Welcome beloved customer!"
#define CUSTOMER_LOGOUT "Logging you out now dear customer! Good bye!$"

#define CUSTOMER_ERROR "ERROR entry ! Please try again!$"

// ADMIN MENU
#define CUSTOMER_MENU "1. Get Customer Details\n2. Deposit Money\n3. Withdraw Money\n4. Get Balance\n5. Get Transaction information\n6. Change Password\n7.handle loan operations\n8.apply_feedback\n9.transfer funds\nPress any other key to logout"

#define ACCOUNT_DEACTIVATED "It seems your account has been deactivated!^"

#define DEPOSIT_AMOUNT "How much is it that you want to add into your bank?"
#define DEPOSIT_AMOUNT_INVALID "You seem to have passed an invalid amount!^"
#define DEPOSIT_AMOUNT_SUCCESS "The specified amount has been successfully added to your bank account!^"

#define WITHDRAW_AMOUNT "How much is it that you want to withdraw from your bank?"
#define WITHDRAW_AMOUNT_INVALID "You seem to have either passed an invalid amount or you don't have enough money in your bank to withdraw the specified amount^"
#define WITHDRAW_AMOUNT_SUCCESS "The specified amount has been successfully withdrawn from your bank account!^"

#define PASSWORD_CHANGE_OLD_PASS "Enter your old password"
#define PASSWORD_CHANGE_OLD_PASS_INVALID "The entered password doesn't seem to match with the old password"
#define PASSWORD_CHANGE_NEW_PASS "Enter the new password"
#define PASSWORD_CHANGE_NEW_PASS_RE "Reenter the new password"
#define PASSWORD_CHANGE_NEW_PASS_INVALID "The new password and the reentered passwords don't seem to pass!^"
#define PASSWORD_CHANGE_SUCCESS "Password successfully changed!^"
#define ADMIN_PASSWORD_CHANGE_SUCCESS "Password successfully changed!"
// ====================================================


#define ACCOUNT_FILE "./database/account.bank"
// #define CUSTOMER_FILE "./database/customer.bank"
#define TRANSACTION_FILE "./database/transactions.bank"

#define EMPLOYEE_FILE "./database/employee.bank"
#define LOAN_FILE "./database/loan.bank"
#define FEEDBACK_FILE "./database/feedback.bank"

#endif