// Rollno:MT2024132
// Name:Sampathkumar T
// Question No 24 of Hands On list 2
// 24. Write a program to create a message queue and print the key and message queue id.
#include <stdio.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/msg.h>

int main() {
    key_t key;//key_t is used to uniquely identify IPC resources, like message queues, shared memory segments, and semaphores.
    int msgid;

    // Generate a unique key for the message queue
    key = ftok("creatingfile.sh", 115); 
    //The project identifier is limited to the range 0 to 255, as it’s represented by an unsigned char.
    //ftok() combines the file’s inode number and the project identifier to generate a unique key. The resulting key is used to identify IPC resources.
    if (key == -1) {
        perror("ftok failed");
        return 1;
    }

    // Create a message queue and get its ID
    msgid = msgget(key, 0666 | IPC_CREAT); // 0666 is the permission mode
    //The msgget() function is used to create a new message queue or access an existing one using the specified key.
    //The msgget function call with IPC_CREAT will create a new message queue with the specified key if one does not already exist.
    //  If a message queue with the specified key already exists, it will return the identifier of the existing queue.
    if (msgid == -1) {
        perror("msgget failed");
        return 1;
    }

    // Print the key and message queue ID
    printf("Key: %d\n", key);
    printf("Message Queue ID: %d\n", msgid);
    //Each message queue has a unique ID, which is an integer value returned by msgget. This ID is used in subsequent IPC operations, 
    // such as sending and receiving messages, to specify which message queue you want to interact with.

    return 0;
}
// ftok: Generates a unique key based on a file and a project identifier.
// msgget: Accesses or creates a message queue based on the key generated by ftok.
// msgsnd: Sends a message to the message queue.
// msgrcv: Receives a message from the message queue.
// msgctl: Controls operations on the message queue, such as removing it or getting its status.